services:
  - type: web
    name: cloudcostguard-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
